spring:
  application:
    name: jpaspring
    profiles:
    active:
      default   
  jpa:
      database: MYSQL
      show-sql: true
      javax:
        persistence:
          sharedCache:
                mode: ENABLE_SELECTIVE
      hibernate:
        ddl-auto: none        
        dialect:  org.hibernate.dialect.MySQLDialect
        generate_statistics: true        
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory  
        connection:
          isolation: 2
  datasource:        
        url: jdbc:mysql://127.0.0.1:3306/socnet?createDatabaseIfNotExist=true&useSSL=false  
        username: root
        password: root        
        driver-class-name: com.mysql.jdbc.Driver
        

        